namespace Com.Coppel.SDPC.Application.Models.Enums;

public enum PuntoDeConsumoTypeVM
{
	SMLC = 1,
	SMCP = 2,
	CONVERSION_LINEA_CREDITO = 3,
	DECREMENTO_LINEA_CREDITO = 4,
	ASIGNACION_LINEAS = 5,
	ASIGNACION_GRUPO = 6,
	FACTORES_SATURACION_CARTERA = 7,
	TDI_MORATORIO_CARTERA = 8,
	TDI_MORATORIO_DCP = 9,
	BONIFICACIONES = 10,


	TDI_CP = 44,
	TDI_CPC = 55,
	TDI_CPPRESTAMO = 999
}
